ichnaea_web_app_prediction_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Default:index }

create_prediction_matrix_form:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:predictionForm}
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"

update_prediction_matrix_form:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/update
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:predictionUpdateForm}
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        prediction_id: "\d+"

update_prediction_matrix_action:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/update
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:predictionUpdateForm}
    requirements:
        _method: POST
        matrix_id: "\d+"
        training_id: "\d+"
        prediction_id: "\d+"
        
create_prediction_matrix_action:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:predictionForm}
    requirements:
        _method: POST
        matrix_id: "\d+"
        training_id: "\d+"

view_matrix_prediction:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:predictionMatrixView}
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        prediction_id: "\d+"

download_training_template:
    pattern: /matrix/{matrix_id}/training/{training_id}/download_template
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:downloadMatrixTemplate}
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"

predictions_user:
     pattern: /my_predictions
     defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:getUserPredictions}
     requirements:
         _method: GET

prediction_send:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/send
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:sendPrediction }
    requirements:
        _method: GET
        matrix_id : "\d+"
        training_id: "\d+"
        prediction_id: "\d+"

prediction_resend:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/resend
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:resendPrediction }
    requirements:
        _method: GET
        matrix_id : "\d+"
        training_id: "\d+"
        prediction_id: "\d+"
 
prediction_view_results:
     pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/results
     defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:viewPredictionResults }
     requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        prediction_id: "\d+"

prediction_download_n_result:
    pattern: /matrix/{matrix_id}/training/{training_id}/prediction/{prediction_id}/results/{index}
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:downloadPredictionResult }
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        prediction_id: "\d+"
        index: "\d+"

list_predictions_system:
    pattern: /system/predictions/{page}
    defaults: { _controller: IchnaeaWebAppPredictionBundle:Prediction:listSystemPredictions }
    requirements: 
        _method: GET
        page: "\d+"
    
