season_list:
    pattern: /season/list
    defaults: { _controller: MatrixBundle:Season:index }

season_form:
    pattern: /season/new
    defaults: { _controller: MatrixBundle:Season:seasonForm }
    requirements:
        _method: GET

season_edit:
    pattern: /season/{season_id}
    defaults: { _controller: MatrixBundle:Season:seasonForm }
    requirements: 
        _method: GET
        season_id: "\d+"
        
season_create:
    pattern: /season/create
    defaults: { _controller: MatrixBundle:Season:createSeason }
    requirements:
        _method: POST
        
season_update:
    pattern: /season/{season_id}/update
    defaults: { _controller: MatrixBundle:Season:updateSeason }
    requirements:
        _method: POST
        season_id: "\d+"
    
variable_list:
    pattern: /variable/list
    defaults: { _controller: MatrixBundle:Variable:getVariablesList }
    requirements:
        _method: GET

variable_new:
    pattern: /variable/new
    defaults: { _controller: MatrixBundle:Variable:getFormVariable }
    requirements:
        _method: GET
    
variable_edit:
    pattern: /variable/{variable_id}
    defaults: { _controller: MatrixBundle:Variable:getFormVariable }
    requirements:
        _method: GET
        
variable_create:
    pattern: /variable/create
    defaults: { _controller: MatrixBundle:Variable:createVariable }
    requirements:
        _method: POST

variable_update:
    pattern: /variable/{variable_id}/update
    defaults: { _controller: MatrixBundle:Variable:updateVariable }
    requirements:
        _method: POST
        variable_id: "\d+"
   
season_set_form:
    pattern: /variable/{variable_id}/season_set
    defaults: { _controller: MatrixBundle:Variable:seasonSetForm }
    requirements:
        _method: GET
        variable_id: "\d+"

season_set_create:
    pattern: /variable/{variable_id}/season_set/
    defaults: { _controller: MatrixBundle:Variable:seasonSetForm }    
    requirements:
         _method: POST
         variable_id: "\d+"
         
season_set_edit:
    pattern: /variable/{variable_id}/season_set/{season_set_id}
    defaults: { _controller: MatrixBundle:Variable:editSeasonSetForm }
    requirements:
        _method: GET
        variable_id: "\d+"
        season_set_id: "\d+"

season_set_update:
     pattern: /variable/{variable_id}/season_set/{season_set_id}
     defaults: { _controller: MatrixBundle:Variable:editSeasonSetForm }
     requirements:
          _method: POST
          variable_id: "\d+"
          season_set_id: "\d+"

season_set_delete_confirmation:
    pattern: /variable/{variable_id}/season_set/{season_set_id}/delete
    defaults: { _controller: MatrixBundle:Variable:seasonSetCompleteDestroyForm }
    requirements: 
        _method: GET
        variable_id: "\d+"
        season_set_id: "\d+"

season_set_delete_action:
    pattern: /variable/{variable_id}/season_set/{season_set_id}/delete
    defaults: { _controller: MatrixBundle:Variable:seasonSetCompleteDestroyForm }
    requirements: 
        _method: POST
        variable_id: "\d+"
        season_set_id: "\d+"            

matrix_form:
    pattern: /matrix
    defaults: { _controller: MatrixBundle:Matrix:getMatrixForm }

matrix_list:
    pattern: /matrix/list
    defaults: { _controller: MatrixBundle:Matrix:listSystemsMatrix }

matrix_create_action:
    pattern: /matrix/create
    defaults: { _controller: MatrixBundle:Matrix:createMatrix }
    requirements:
        _method: POST
    
matrix_ui_edit:
    pattern: /matrix/{matrix_id}/edit
    defaults: { _controller: MatrixBundle:Matrix:guiMatrix }
    requirements:
        _method: GET
        matrix_id: "\d+"

matrix_ui_edit_submit:
    pattern: /matrix/{matrix_id}/edit
    defaults: { _controller: MatrixBundle:Matrix:guiMatrix }
    requirements:
        _method: POST
        matrix_id: "\d+"

matrix_ui_view:
    pattern: /matrix/{matrix_id}
    defaults: { _controller: MatrixBundle:Matrix:viewMatrix }
    requirements:
        _method: GET
        matrix_id: "\d+"

matrix_save_configuration:
    pattern: /matrix/{matrix_id}/save
    defaults: { _controller: MatrixBundle:Matrix:saveConfiguration }
    requirements: 
        _method: POST
        matrix_id: "\d+"

matrix_build_files:
    pattern: /matrix/{matrix_id}/build_files
    defaults: { _controller: MatrixBundle:Matrix:buildFiles}
    requirements:
        _method: POST
        matrix_id: "\d+"
    

matrix_download_form:
    pattern: /matrix/{matrix_id}/download
    defaults: { _controller: MatrixBundle:Matrix:downloadForm}
    requirements: 
        _method: GET
        matrix_id: "\d+"

matrix_download:
    pattern: /matrix/{matrix_id}/downloading
    defaults: { _controller: MatrixBundle:Matrix:download }
    requirements: 
        _method: POST
        matrix_id: "\d+"

clone_matrix_form:
    pattern: /matrix/{matrix_id}/clone
    defaults: { _controller: MatrixBundle:Matrix:cloneForm }
    requirements: 
       _method: GET
       matrix_id: "\d+"

perform_clone_matrix:
    pattern: /matrix/{matrix_id}/performClone
    defaults: { _controller: MatrixBundle:Matrix:performClone }
    requirements: 
       _method: POST
       matrix_id: "\d+"
