ichnaea_web_app_training_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IchnaeaWebAppTrainingBundle:Default:index }

create_training_form:
    pattern: /matrix/{matrix_id}/training
    defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:trainingForm }
    requirements: 
        _method: GET
        matrix_id: "\d+"

submit_training:
    pattern: /matrix/{matrix_id}/training
    defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:trainingForm}
    requirements:
        _method: POST
        matrix_id: "\d+"
                
training_view:
    pattern: /matrix/{matrix_id}/training/{training_id}
    defaults: {_controller: IchnaeaWebAppTrainingBundle:Training:viewTraining, check: false }
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        
training_check:
    pattern: /matrix/{matrix_id}/training/{training_id}
    defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:viewTraining, check: true }
    requirements:
        _method: POST
        matrix_id: "\d+"
        training_id: "\d+"

resend_training:
    pattern: /matrix/{matrix_id}/training/{training_id}/resend
    defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:resendTraining, check: true }
    requirements:
        _method: GET
        matrix_id: "\d+"
        training_id: "\d+"
        
training_delete:
     pattern: /matrix/{matrix_id}/training/{training_id}/delete
     defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:deleteTraining}
     requirements:
         _method: GET
         matrix_id: "\d+"
         training_id: "\d+"

training_delete_submit:
     pattern: /matrix/{matrix_id}/training/{training_id}/delete/submit
     defaults: { _controller: IchnaeaWebAppTrainingBundle:Training:submitDeleteTraining}
     requirements:
         _method: GET
         matrix_id: "\d+"
         training_id: "\d+"