fos_user_security:
     resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
     prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

user_dashboard:
    path: /dashboard
    defaults: { _controller: UserBundle:Dashboard:getDashboard }
    
user_list:
    path: /users
    defaults: { _controller: UserBundle:Users:getUsersList }

edit_user:
    path: /user/{user_id}
    defaults: { _controller: UserBundle:Users:editUser }
    