ichnaea_web_app_training:
    resource: "@IchnaeaWebAppTrainingBundle/Resources/config/routing.yml"
    prefix:   /

ichnaea_api:
    resource: "@IchnaeaApiBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
matrix:
    resource: "@MatrixBundle/Resources/config/routing.yml"
    prefix:   /
    
home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dashboard
        permanent: true
        