ichnaea_api:
    resource: "@IchnaeaApiBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

matrix:
    resource: "@MatrixBundle/Resources/config/routing.yml"
    prefix:   /
    
home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true