#jms_security_extra:
#    secure_all_services: false
#	    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        #Ichnaea\WebApp\UserBundle\Entity\User:
        #    id: my_user_password_encoder
        #Symfony\Component\Security\Core\User\User: plaintext

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #users:
        #entity: { class: Ichnaea\WebApp\UserBundle\Entity\User, property: login }
        fos_userbundle:
            id: fos_user.user_provider.username

    #firewalls:
    #    login: 
    #        pattern: ^/login$
    #        anonymous: true
    #        security: false
    #        
    #    main:
    #        pattern: ^/.*$
    #        provider: users
    #        form_login:
    #            login_path: /login
    #            check_path: /login_check
    #            remember_me: true
    #            default_target_path: /matrix/list
    #        logout:
    #            path: /logout
    #            target: /login
    #        remember_me:
    #            key: MiPassphrase
    #            lifetime: 1800
    #            path: /
    #            domain: ~
    #        security: true
    #        anonymous: true
    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                default_target_path: /variable/list
                #csrf_provider: form.csrf_provider
            logout: true
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /
                domain: ~
            anonymous: true
    
    access_control:
        - { path: /login.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_REMEMBERED }
