season_api:
    pattern: /api/season/
      
season_content:
    pattern: /api/season/{id}
    defaults: { _controller: IchnaeaApiBundle:Api:getSeason,  _format: json }
    requirements:
        _method: GET
        id: "\d+"

#@TODO Change method to GET
season_search_by_name:
    pattern: /api/season/searchByName
    defaults: { _controller: IchnaeaApiBundle:Api:getSeasonByPatternName, _format: json }
    requirements:
        _method: POST

season_set_api:
     pattern: /api/variable/{{variable_id}}/seasonSet/
     requirements:
         variable_id: "\d+"

season_set_delete:
    pattern: /api/variable/{variable_id}/seasonSet/{seasonSet_id}
    defaults: { _controller: IchnaeaApiBundle:Api:deleteSeasonSet, _format: json }
    requirements:
        _method: DELETE

season_set_component_delete:
    pattern: /api/variable/{variable_id}/seasonSet/{seasonSet_id}/component/{component_id}
    defaults: { _controller: IchnaeaApiBundle:Api:deleteSeasonSetComponent, _format: json }
    requirements:
        _method: DELETE
