variable_api:
    pattern: /api/variable/
    
season_api:
    pattern: /api/season/
      
season_content:
    pattern: /api/season/{id}
    defaults: { _controller: IchnaeaApiBundle:Api:getSeason,  _format: json }
    requirements:
        _method: GET
        id: "\d+"

#@TODO Change method to GET
season_search_by_name:
    pattern: /api/season/searchByName
    defaults: { _controller: IchnaeaApiBundle:Api:getSeasonByPatternName, _format: json }
    requirements:
        _method: POST

season_set_api:
     pattern: /api/variable/{variable_id}/seasonSet/
     defaults: { _controller: IchnaeaApiBundle:Api:getVariableSeasonSet, _format: json }
     requirements:
         variable_id: "\d+"
         _method: GET

season_set_delete:
    pattern: /api/variable/{variable_id}/seasonSet/{seasonSet_id}
    defaults: { _controller: IchnaeaApiBundle:Api:deleteSeasonSet, _format: json }
    requirements:
        _method: DELETE

season_set_component_delete:
    pattern: /api/variable/{variable_id}/seasonSet/{seasonSet_id}/component/{component_id}
    defaults: { _controller: IchnaeaApiBundle:Api:deleteSeasonSetComponent, _format: json }
    requirements:
        _method: DELETE

season_set_component_delete_complete:
    pattern: /api/variable/{variable_id}/seasonSet/{seasonSet_id}/component/{component_id}/complete
    defaults: { _controller: IchnaeaApiBundle:Api:deleteSeasonSetComponentCascade, _format: json }
    requirements:
        _method: DELETE


matrix_api:
    pattern: /api/matrix/{matrix_id}
    requirements:
        matrix_id: "\d+"
        
matrix_column:
    pattern: /api/matrix/{matrix_id}/column/{column_id}
    defaults: { _controller: IchnaeaApiBundle:Api:updateMatrixColumn, _format: json }
    requirements:
        _method: PUT
        matrix_id: "\d+"
        column_id: "\d+"

sample_api:
    pattern: /api/matrix/{matrix_id}/sample/
    requirements: 
        matrix_id: "\d+"

sample_update:
    pattern: /api/matrix/{matrix_id}/sample/{sample_id}
    defaults: { _controller: IchnaeaApiBundle:Api:updateSample, _format: json }
    requirements:
        _method: PUT
        matrix_id: "\d+"
        sample_id: "\d+"
