parameters:
#    ichnaea_api.example.class: Ichnaea\ApiBundle\Example

services:
#    ichnaea_api.example:
#        class: %ichnaea_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
